INSERT INTO company (ID, NAME) VALUES (1, 'EXIMBAY');



INSERT INTO division (DIVISION_SEQ,  NAME) VALUES (1, 'D1');

INSERT INTO division (DIVISION_SEQ,  NAME) VALUES (2, 'D2');


INSERT INTO team2 (TEAM_SEQ,DIVISION_SEQ,  NAME, LOCAL_NAME,TEAM_TYPE, USE_FLAG) VALUES (1, 1, 'TEAM 1','1T' ,'TFT','Y');

INSERT INTO team2 (TEAM_SEQ,DIVISION_SEQ,  NAME, LOCAL_NAME,TEAM_TYPE, USE_FLAG) VALUES (2, 2, 'TEAM 2','2T', 'SQUAD','N');

INSERT INTO member2 (MEMBER_SEQ, NAME) VALUES(1111,'Jane');
INSERT INTO member2 (MEMBER_SEQ, NAME) VALUES(2222,'Bob');
INSERT INTO member2 (MEMBER_SEQ, NAME) VALUES(3333,'Chris');



INSERT INTO TEAM_MEMBER (APPLY_BEGIN_DATE,TEAM_MANAGER_FLAG,TEAM_SEQ,MEMBER_SEQ) VALUES(1,'Y', 1,1111);
INSERT INTO TEAM_MEMBER (APPLY_BEGIN_DATE, TEAM_MANAGER_FLAG,TEAM_SEQ,MEMBER_SEQ) VALUES(2, 'N',2,2222);
INSERT INTO TEAM_MEMBER (APPLY_BEGIN_DATE,TEAM_MANAGER_FLAG,TEAM_SEQ,MEMBER_SEQ) VALUES(3, 'Y',1,3333);

-- INSERT INTO TEAM_MEMBER (TEAM_SEQ,MEMBER_SEQ) VALUES(1,1111);
-- INSERT INTO TEAM_MEMBER (TEAM_SEQ,MEMBER_SEQ) VALUES(2,2222);
-- INSERT INTO TEAM_MEMBER (TEAM_SEQ,MEMBER_SEQ) VALUES(1,3333);


/*
INSERT INTO team2 (TEAM_SEQ,DIVISION_SEQ,  NAME, LOCAL_NAME,TEAM_TYPE, USE_FLAG) VALUES (1, 1, 'TEAM 1','1T' ,'TFT','Y');

INSERT INTO team2 (TEAM_SEQ,DIVISION_SEQ,  NAME, LOCAL_NAME,TEAM_TYPE, USE_FLAG) VALUES (2, 2, 'TEAM 2','2T', 'SQUAD','N');

INSERT INTO member2 (MEMBER_SEQ, TEAM_SEQ, NAME) VALUES(1111,1,'Jane');
INSERT INTO member2 (MEMBER_SEQ, TEAM_SEQ, NAME) VALUES(2222,2,'Bob');
INSERT INTO member2 (MEMBER_SEQ, TEAM_SEQ, NAME) VALUES(3333,1,'Chris');


*/

/* INSERT INTO team (ID, NAME, REG_USER_ID, REG_DT) VALUES (1, 'TEAM 1', 'bayar', now());

INSERT INTO member (ID, TEAM_ID, LEVEL, USER_ID, PASSWORD, NAME, EMAIL, REG_USER_ID, REG_DT)VALUES(1, 1, 'C', 'admin', '123456', 'Admin', 'admin@eximbay.com', 'bayar', now());
INSERT INTO member (ID, TEAM_ID, LEVEL, USER_ID, PASSWORD, NAME, EMAIL, REG_USER_ID, REG_DT)VALUES(2, 1, 'T', 'bayar', '123456', 'Bayar', 'bayar@eximbay.com', 'bayar', now());
INSERT INTO member (ID, TEAM_ID, LEVEL, USER_ID, PASSWORD, NAME, EMAIL, REG_USER_ID, REG_DT)VALUES(3, 1, 'M', 'tester', '123456', 'Tester', 'test@eximbay.com', 'bayar', now());
INSERT INTO member (ID, TEAM_ID, LEVEL, USER_ID, PASSWORD, NAME, EMAIL, REG_USER_ID, REG_DT)VALUES(4, 1, 'M', 'tester2', '123456', 'Tester2', 'test2@eximbay.com', 'bayar', now());
INSERT INTO member (ID, TEAM_ID, LEVEL, USER_ID, PASSWORD, NAME, EMAIL, REG_USER_ID, REG_DT)VALUES(5, 1, 'M', 'tester3', '123456', 'Tester3', 'test3@eximbay.com', 'bayar', now());
  */
/*INSERT INTO objective (ID, M_ID, OBJ_NO, OBJ_NAME, LEVEL, REG_USER_ID, REG_DT)VALUES(1, 1, '1', 'Test Obj 1', 'M', 'bayar', now());
INSERT INTO objective (ID, M_ID, OBJ_NO, OBJ_NAME, LEVEL, REG_USER_ID, REG_DT)VALUES(2, 1, '2', 'Test Obj 2', 'M', 'bayar', now());
INSERT INTO objective (ID, M_ID, OBJ_NO, OBJ_NAME, LEVEL, REG_USER_ID, REG_DT)VALUES(3, 1, '3', 'Test Obj 3', 'M', 'bayar', now());

INSERT INTO key_result (ID, KR_NO, KR_NAME, PCT_OF_KR_COMPLETE, REG_USER_ID, REG_DT)VALUES(1, '1', 'Test KR 1', 80, 'bayar', now());
INSERT INTO key_result (ID, KR_NO, KR_NAME, PCT_OF_KR_COMPLETE, REG_USER_ID, REG_DT)VALUES(2, '2', 'Test KR 2', 76, 'bayar', now());
INSERT INTO key_result (ID, KR_NO, KR_NAME, PCT_OF_KR_COMPLETE, REG_USER_ID, REG_DT)VALUES(3, '3', 'Test KR 3', 78, 'bayar', now());
*/